services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./www/:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: dwp_final
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./dwp_final.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ''
    depends_on:
      - db

volumes:
  mariadb_data: